version: "3.8"
services:
  backend:
    container_name: golang-todo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    command: sh -c "go run main.go"
    ports:
      - 8080:8080
